models.py
import pymysql
from settings import *

class DBConnect:
    def __init__(self):
        self.open()
        self.cursor.execute("CREATE TABLE IF NOT EXISTS produk(produk_id INT AUTO_INCREMENT PRIMARY KEY, nama_produk VARCHAR(255), keterangan TEXT, harga INT(20), jumlah INT(6))")
        self.connection.commit()
        self.close()
    
    def open(self):
        self.connection = pymysql.connect(host=DB_HOST, user=DB_USER, password=DB_PASS, db=DB_NAME)
        self.cursor = self.connection.cursor()
    
    def close(self):
        self.connection.close()

class Product(DBConnect):
    def __init__(self, produk_id = None, nama_produk = None, keterangan = None, harga = None, jumlah = None):
        self.id = produk_id
        self.name = nama_produk
        self.description = keterangan
        self.price = harga
        self.stock = jumlah
    
    @classmethod
    def find_all(cls):
        try:
            connect = DBConnect()
            connect.open()
            connect.cursor.execute("SELECT * FROM produk")
            result = connect.cursor.fetchall()
            connect.close()
            return [
                cls(x[0], x[1], x[2], x[3], x[4])
                for x in result
            ]
        except Exception as err:
            print(err)
            raise err
    
    @classmethod
    def find_one(cls, produk_id):
        try:
            connect = DBConnect()
            connect.open()
            connect.cursor.execute("SELECT * FROM produk WHERE produk_id=%s", (produk_id,))
            result = connect.cursor.fetchone()
            connect.close()
            if result:
                return cls(result[0], result[1], result[2], result[3], result[4])
        except Exception as err:
            print(err)
            raise err
    
    def save(self):
        try:
            self.open()
            self.cursor.execute("INSERT INTO produk(nama_produk, keterangan, harga, jumlah) VALUES (%s, %s, %s, %s)", (self.name, self.description, self.price, self.stock,))
            self.connection.commit()
            self.cursor.execute("SELECT LAST_INSERT_ID()")
            self.id = self.cursor.fetchone()
            self.close()
            return True
        except Exception as err:
            print(err)
            raise err
    
    def update(self):
        try:
            self.open()
            self.cursor.execute("UPDATE produk SET nama_produk=%s, keterangan=%s, harga=%s, jumlah=%s WHERE produk_id=%s", (self.name, self.description, self.price, self.stock, self.id,))
            self.connection.commit()
            self.close()
            return True
        except Exception as err:
            print(err)
            raise err
    
    @classmethod
    def delete(cls, produk_id):
        try:
            connect = DBConnect()
            connect.open()
            connect.cursor.execute("DELETE FROM produk WHERE produk_id=%s", (produk_id,))
            connect.connection.commit()
            connect.close()
            return cls()
        except Exception as err:
            print(err)
            raise err
    
    def __bool__(self):
        return None not in [self.id, self.name, self.description, self.price, self.stock]

main.py
from flask import Flask
from views import views as product_module

app = Flask(__name__)

app.register_blueprint(product_module)

if __name__ == '__main__':
    app.run(debug=True, port=5500)

views.py
from flask import Blueprint, redirect, url_for, request, render_template, jsonify
from models import Product

views = Blueprint('views', __name__, url_prefix='')

@views.route('/')
def index():
    return redirect(url_for('views.get_products'))

@views.route('/products', methods=['GET'])
def get_products():
    products = Product.find_all()
    return render_template('index.html', products=products)

@views.route('/products', methods=['POST'])
def insert_product():
    product = Product(nama_produk=request.form['nama_produk'], keterangan=request.form['keterangan'], harga=int(request.form['harga']), jumlah=int(request.form['jumlah']))
    product.save()
    return redirect(url_for('views.get_products'))

@views.route('/products/<int:produk_id>', methods=['GET'])
def get_product(produk_id):
    product = Product.find_one(produk_id)
    if product:
        return jsonify({
            'product_id': product.id,
            'name': product.name,
            'description': product.description,
            'price': product.price,
            'stock': product.stock
        })
    return jsonify({})

@views.route('/products/<int:produk_id>', methods=['PUT', 'PATCH'])
def update_product(produk_id):
    product = Product.find_one(produk_id)
    if product:
        product.name = request.form['nama_produk']
        product.description = request.form['keterangan']
        product.price = int(request.form['harga'])
        product.stock = int(request.form['jumlah'])
        product.update()
    return jsonify({
        'error': None
    })

@views.route('/products/<int:produk_id>', methods=['DELETE'])
def delete_product(produk_id):
    product = Product.find_one(produk_id)
    if product:
        Product.delete(product.id)
    return jsonify({
        'error': None
    })

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <title>Products</title>
</head>
<body>
  <div class="modal fade" id="tambahProduk" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <form action="{{ url_for('views.insert_product') }}" method="post">
        <div class="modal-header">
          <h5 class="modal-title">Tambah Produk</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <input class="form-control mt-1" name="nama_produk" type="text" placeholder="Nama Produk">
            <textarea class="form-control mt-2" name="keterangan" rows="3" placeholder="Keterangan"></textarea>
            <div class="row mt-2">
              <div class="col-sm-6"><input class="form-control" name="harga" type="text" placeholder="Rp."></div>
              <div class="col-sm-6"><input class="form-control" name="jumlah" type="text" placeholder="Jumlah"></div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="editProduk" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <form>
        <div class="modal-header">
          <h5 class="modal-title">Tambah Produk</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <input type="hidden" id="edit_product_id" name="product_id">
            <input class="form-control mt-1" id="edit_nama_produk" name="nama_produk" type="text" placeholder="Nama Produk">
            <textarea class="form-control mt-2" id="edit_keterangan" name="keterangan" rows="3" placeholder="Keterangan"></textarea>
            <div class="row mt-2">
              <div class="col-sm-6"><input class="form-control" id="edit_harga" name="harga" type="text" placeholder="Rp."></div>
              <div class="col-sm-6"><input class="form-control" id="edit_jumlah" name="jumlah" type="text" placeholder="Jumlah"></div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary" onclick="updateProduct()">Simpan</button>
          </div>
        </form>
      </div>
    </div>
  </div>

  <div class="container mt-5">
    <div class="card">
      <div class="card-header">
        <span class="card-title">Daftar Produk</span>
      </div>
      <div class="card-body">
        <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#tambahProduk">Tambah Produk</button>
        <table class="table table-hover table-bordered mt-2">
          <thead>
            <th>No</th>
            <th>Nama Produk</th>
            <th>Keterangan</th>
            <th>Harga <small>(Rp.)</small></th>
            <th>Jumlah</th>
            <th>Aksi</th>
          </thead>
          <tbody>
            {% for product in products %}
              <tr>
                <td>{{ loop.index }}</td>
                <td>{{ product.name }}</td>
                <td>{{ product.description }}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.stock }}</td>
                <td>
                  <button id="edit" class="btn btn-primary" productId="{{ product.id }}" onclick="editProduct(this)" data-bs-toggle="modal" data-bs-target="#editProduk">Edit</button>
                  <button id="delete" class="btn btn-danger" productId="{{ product.id }}" onclick="deleteProduct(this)">Hapus</button>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
</body>
</html>